// GENERADO por «07. App GBH/exportar_bo.py» desde «bo_respuestas.csv». NO EDITAR A MANO: se regenera.
// Fuente: md5 af42dfe0cd94 · exportadas 7 (7 ya publicadas en la app, 0 firmadas) · la frontera ética es SENSIBLE_RE de gbh_personalizar.py.
export const _BO_RESP = [
  {"id": "cantidades", "contexto": ["receta"], "planes": ["free", "standard", "premium"], "condicion": "", "anexo_de": "", "accion": "ninguna", "boton": {"es": "¿Esto es para mí o para varios días?", "en": "Is this all for me, or for several days?"}, "texto": {"es": "Las cantidades ya vienen ajustadas a TU ración. {caja_racion}", "en": "The amounts already come adjusted to YOUR portion. {caja_racion}"}, "firma": "publicado"},
  {"id": "registrar", "contexto": ["inicio"], "planes": ["free", "standard", "premium"], "condicion": "", "anexo_de": "", "accion": "abrir:daily", "boton": {"es": "¿Qué marco si no he comido lo que ponía?", "en": "What do I log if I didn't eat what the plan said?"}, "texto": {"es": "No hace falta que salga perfecto. Marca lo que has hecho de verdad: lo que cuenta es registrar, no cumplir. Un día regular, registrado, vale más que un día perfecto sin registrar.", "en": "It doesn’t need to be perfect. Log what you actually did: what counts is logging, not complying. An average day, logged, is worth more than a perfect day unlogged."}, "firma": "publicado"},
  {"id": "lista", "contexto": ["inicio"], "planes": ["standard", "premium"], "condicion": "", "anexo_de": "", "accion": "abrir:lista", "boton": {"es": "¿Dónde está la lista de la compra?", "en": "Where's the shopping list?"}, "texto": {"es": "Se hace sola con tu semana — marca los ingredientes mientras compras.", "en": "It builds itself from your week — tick off ingredients as you shop."}, "firma": "publicado"},
  {"id": "pausa", "contexto": ["inicio"], "planes": ["free", "standard", "premium"], "condicion": "", "anexo_de": "", "accion": "ninguna", "boton": {"es": "Me voy unos días: ¿pierdo la racha?", "en": "I'm away a few days: do I lose my streak?"}, "texto": {"es": "¿Vacaciones, un viaje, una semana complicada? Decláralo por adelantado y esos días no rompen tu racha. Gratis, sin gemas: el descanso no se paga. El escudo (💎) cubre el despiste de un día. La pausa cubre la vida.", "en": "Holidays, a trip, a tough week? Declare it in advance and those days won't break your streak. Free, no gems: rest is not something you pay for. The shield (💎) covers a one-day slip. The pause covers life."}, "firma": "publicado"},
  {"id": "peso", "contexto": ["inicio"], "planes": ["free", "standard", "premium"], "condicion": "", "anexo_de": "", "accion": "ninguna", "boton": {"es": "¿Cuándo me peso?", "en": "When do I weigh myself?"}, "texto": {"es": "La báscula se abre los miércoles y el fin de semana. Un consejo: pésate siempre a la misma hora, en ayunas — y mira la línea de varias semanas, nunca un solo día.", "en": "The scale opens on Wednesdays and at the weekend. A tip: weigh yourself always at the same time, fasted — and look at the line over several weeks, never a single day."}, "firma": "publicado"},
  {"id": "no_quiero", "contexto": ["inicio"], "planes": ["standard"], "condicion": "", "anexo_de": "", "accion": "abrir:config", "boton": {"es": "No quiero un alimento en mi plan", "en": "I don't want a food in my plan"}, "texto": {"es": "Ahora baja hasta «Alimentos que no quieres» y añade lo que no te guste o te dé alergia. Lo que pongas ahí no aparece nunca en tu programación: ni el alimento ni las recetas que lo llevan.", "en": "Now scroll down to «Foods you don’t want» and add anything you dislike or are allergic to. Whatever you put there never shows up in your plan — neither the food nor any recipe that uses it."}, "firma": "publicado"},
  {"id": "consulta", "contexto": ["inicio"], "planes": ["free", "standard"], "condicion": "", "anexo_de": "", "accion": "abrir:consulta", "boton": {"es": "¿Puedo hablar con Alejandro?", "en": "Can I talk to Alejandro?"}, "texto": {"es": "Esta pestaña es la línea directa con Alejandro — es la parte del plan Premium: consulta presencial, seguimiento semanal y su WhatsApp.", "en": "This tab is the direct line to Alejandro — it’s the Premium side of the plan: in-person consultation, weekly follow-up and his WhatsApp."}, "firma": "publicado"},
];
export const _BO_SENSIBLE = new RegExp("dolor|mareo|náusea|nausea|vómit|vomit|médic|medic|hospital|lesión|lesion|ansiedad|deprimid|triste|llorar|embaraz|regla|menstrua|medicación|medicacion|pastilla|tiroide|diabet|alergi|intoleran", "i");
